// Copyright (c) Thomas Nieto - All Rights Reserved
// You may use, distribute and modify this code under the
// terms of the MIT license.

using System.Collections;
using System.Management.Automation;

namespace OpenDsc.Authoring.Commands;

/// <summary>
/// Creates a DSC resource instance from a type name and a set of properties.
/// The instance can be a typed object generated by <c>Import-DscResourceType</c>
/// or a hashtable of property key-value pairs.
/// </summary>
/// <example>
/// <code>
/// # From a typed object
/// Import-DscResourceType
/// $svc = [DSC.OpenDsc.Windows.Service]@{ Name = 'sshd'; Status = 'Running' }
/// $instance = New-DscResourceInstance -Type 'OpenDsc.Windows/Service' -Instance $svc
///
/// # From a hashtable
/// $instance = New-DscResourceInstance -Type 'OpenDsc.Windows/Service' -Properties @{
///     name = 'sshd'
///     status = 'Running'
/// }
/// </code>
/// </example>
[Cmdlet(VerbsCommon.New, "DscResourceInstance")]
[OutputType(typeof(DscResourceInstanceInfo))]
public sealed class NewDscResourceInstanceCommand : PSCmdlet
{
    /// <summary>
    /// The fully qualified DSC resource type (e.g. <c>OpenDsc.Windows/Service</c>).
    /// When omitted and <see cref="Instance"/> is a generated <c>DSC.*</c> type,
    /// the resource type is inferred from the .NET type name.
    /// </summary>
    [Parameter(Position = 0)]
    [ValidateNotNullOrEmpty]
    public string? Type { get; set; }

    /// <summary>
    /// A typed object from a generated <c>DSC.*</c> type, or a <see cref="PSObject"/> wrapping one.
    /// Mutually exclusive with <see cref="Properties"/>.
    /// </summary>
    [Parameter(ValueFromPipeline = true)]
    public PSObject? Instance { get; set; }

    /// <summary>
    /// A hashtable of property key-value pairs.
    /// Mutually exclusive with <see cref="Instance"/>.
    /// </summary>
    [Parameter]
    public Hashtable? Properties { get; set; }

    /// <inheritdoc/>
    protected override void ProcessRecord()
    {
        if (Instance is null && Properties is null)
        {
            WriteError(new ErrorRecord(
                new ArgumentException("Specify either -Instance or -Properties."),
                "MissingInstanceOrProperties",
                ErrorCategory.InvalidArgument,
                null));

            return;
        }

        // Infer -Type from the DSC.* type name if not explicitly provided
        var resolvedType = Type ?? TryInferTypeFromInstance();

        if (string.IsNullOrEmpty(resolvedType))
        {
            WriteError(new ErrorRecord(
                new ArgumentException(
                    "Cannot infer the resource type. Specify -Type explicitly, or use a generated DSC.* typed object."),
                "CannotInferResourceType",
                ErrorCategory.InvalidArgument,
                null));

            return;
        }

        var dict = ExtractProperties();

        if (dict is null)
        {
            return;
        }

        var info = new DscResourceInstanceInfo
        {
            Type = resolvedType,
            Properties = dict,
        };

        WriteObject(info);
    }

    private string? TryInferTypeFromInstance()
    {
        if (Instance is null)
        {
            return null;
        }

        var typeName = Instance.BaseObject.GetType().FullName;

        if (typeName is null || !typeName.StartsWith("DSC.", StringComparison.Ordinal))
        {
            return null;
        }

        return DscDiscoveredResource.FromTypeName(typeName);
    }

    private Dictionary<string, object?>? ExtractProperties()
    {
        if (Properties is not null)
        {
            return ConvertHashtable(Properties);
        }

        if (Instance is null)
        {
            return null;
        }

        var baseObj = Instance.BaseObject;

        // If it's a hashtable, convert directly
        if (baseObj is Hashtable ht)
        {
            return ConvertHashtable(ht);
        }

        // Otherwise, reflect the properties from the typed object
        var dict = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
        var type = baseObj.GetType();

        foreach (var prop in type.GetProperties(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance))
        {
            if (!prop.CanRead)
            {
                continue;
            }

            var value = prop.GetValue(baseObj);

            // Skip null properties to keep output clean
            if (value is null)
            {
                continue;
            }

            // Use camelCase for property names in the config document
            var name = char.ToLowerInvariant(prop.Name[0]) + prop.Name[1..];
            dict[name] = ConvertValue(value);
        }

        return dict;
    }

    private static Dictionary<string, object?> ConvertHashtable(Hashtable ht)
    {
        var dict = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);

        foreach (DictionaryEntry entry in ht)
        {
            var key = entry.Key.ToString() ?? string.Empty;
            dict[key] = ConvertValue(entry.Value);
        }

        return dict;
    }

    /// <summary>
    /// Converts enum values to their string representation for JSON serialization.
    /// </summary>
    private static object? ConvertValue(object? value)
    {
        if (value is null)
        {
            return null;
        }

        // Convert enum values to strings so they serialize as "Running" not 0
        if (value.GetType().IsEnum)
        {
            return value.ToString();
        }

        return value;
    }
}

/// <summary>
/// Intermediate representation of a DSC resource instance before it is added to a configuration.
/// Holds the resource type and its properties in a dictionary form.
/// </summary>
public sealed class DscResourceInstanceInfo
{
    /// <summary>
    /// The fully qualified DSC resource type (e.g. <c>OpenDsc.Windows/Service</c>).
    /// </summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>
    /// The resource properties as a key-value dictionary.
    /// </summary>
    public Dictionary<string, object?> Properties { get; set; } = [];
}
