name: OpenDsc Windows User Resource CI

on:
  pull_request:
    paths:
      - 'src/OpenDsc.Resource.Windows.User/**'
      - 'tests/integration/OpenDsc.Resource.Windows.User.tests.ps1'
      - 'build.ps1'
      - '.github/workflows/windows-user-ci.yml'

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'
        
    - name: Run integration tests
      shell: pwsh
      run: |
        ./build.ps1 -ProjectName "OpenDsc.Resource.Windows.User" -Test -Verbose